name: terraform
on:
  push:
    branches:
      - master
defaults:
  run:
    working-directory: ./
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: authenticating to google
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: github commands
        run: |
          git config --global user.password ${{ secrets.TOKEN }}
          git config --global credential.helper store
      - name: initilization
        run: terraform init