name: terraform
on:
  push:
    branches:
      - master
defaults:
  run:
    working-directory: ./
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: authenticating to google
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Configure Git 
        run: |
          echo "machine github.com login username password ${TOKEN}" > ~/.netrc
          git config --global url."https://github.com/".insteadOf "git://github.com/"
          git config --global advice.detachedHead false
        env:
          TOKEN: ${{ secrets.TOKEN }}
      - name: initilization
        run: terraform init